### ISSUE TITLE
This is very cool, but can be better 📦 

### ISSUE THREAD

**Issue by G3NSVRV** [nicolasdejong/ShakeMouseToLocate#1]
Maybe can be changed to use the new api instead of the old to get maybe resize in the future form the api:

https://docs.microsoft.com/en-us/uwp/api/windows.ui.core.corecursor?view=winrt-19041

**Comment by nicolasdejong** [comment]
Yes, currently the cursor is not altered but an image is drawn on the same location. That is not ideal, but there are various reasons to do it like that instead of using the cursor api:

- The size of a cursor is limited. And it should be big. Very big.
- The change of cursor typically only happens when the cursor is moved. Having a nice growing/shrinking animation then is not possible
- Defensive: if this application happens to crash at least the cursor is still intact so the user is not forced to restart Windows

For these reasons I think it not wise to use the api you mentioned. But thanks for the suggestion.
